name: Deploy - Production - texttocases.velloware.com

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Copy repository contents via scp
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          PORT: ${{ secrets.PORT }}
          source: '.'
          target: '/var/www/texttocases.velloware.com'
          overwrite: true
      - name: Executing remote command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          PORT: ${{ secrets.PORT }}
          script: ls

      - name: Deployng the project branch ${{ github.ref_name }} in /var/www/texttocases.velloware.com
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          PORT: ${{ secrets.PORT }}
          script: |
            sudo chown -R $USER /var/www/texttocases.velloware.com
            cd /var/www/texttocases.velloware.com
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            npm ci i
            npm run build
            curl --request POST --url ${{ secrets.VELLODASH }} --header 'Content-Type: application/json' --data '{"message": "\n Deploing TextToCases Frontend - ⛑${{ github.ref_name }}📣📢\n on Vello-1-server (acess: texttocases.velloware.com)"}'
